package routers

import (
	"github.com/gin-gonic/gin"
	"github.com/mtami/go-crud/controllers"

	_ "github.com/mtami/go-crud/docs" // docs is generated by Swag CLI, you have to import it.
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func SetupRouter() *gin.Engine {
	router := gin.Default()

	v1 := router.Group("/v1")
	{
		posts := v1.Group("/posts")
		{
			posts.GET("", controllers.ListPost)
			posts.POST("", controllers.AddNewPost)
			posts.GET("/:id", controllers.GetOnePost)
			posts.PUT("/:id", controllers.PutOnePost)
			posts.DELETE("/:id", controllers.DeletePost)
		}

	}

	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	return router
}
